-- Synthetic local-only PG17 fixture. No production records or credentials.
CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE service_role NOLOGIN;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('request.jwt.claim.sub',true),'')::uuid
$$;
CREATE TABLE public.profiles (id uuid PRIMARY KEY, role text NOT NULL);
CREATE FUNCTION public.is_admin() RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND role='admin')
$$;
CREATE FUNCTION public.is_customer_role() RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND role='customer')
$$;
CREATE TABLE public.customers (id bigint PRIMARY KEY, name text);
CREATE TABLE public.products (
  id bigint PRIMARY KEY, stock integer NOT NULL DEFAULT 0,
  product_type text DEFAULT 'stock', is_bundle boolean DEFAULT false
);
CREATE TABLE public.warehouses (id integer PRIMARY KEY);
CREATE TABLE public.product_bundles (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  bundle_id bigint NOT NULL, child_product_id bigint NOT NULL, qty numeric NOT NULL
);
CREATE TABLE public.sales (
  id bigint PRIMARY KEY,
  order_no text UNIQUE,
  customer_id bigint REFERENCES public.customers(id),
  customer_name text,
  total_amount numeric(12,2), subtotal numeric(12,2), discount_amount numeric(12,2),
  paid_amount numeric(12,2), change_amount numeric(12,2), credit_used_amount numeric(14,2),
  vat_amount numeric(15,2), vat_rate numeric(5,2), is_credit boolean DEFAULT false,
  stock_reverted_at timestamptz, note text
);
CREATE TABLE public.sale_items (
  id bigint PRIMARY KEY, sale_id bigint NOT NULL REFERENCES public.sales(id),
  product_id bigint, product_name text, qty integer, unit_price numeric,
  line_total numeric, warehouse_id bigint
);
CREATE TABLE public.refunds (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  refund_no text UNIQUE, sale_id bigint REFERENCES public.sales(id),
  customer_id bigint REFERENCES public.customers(id), customer_name text,
  reason text, refund_method text, refund_amount numeric,
  items_json jsonb, restocked boolean DEFAULT false, warehouse_id bigint,
  note text, created_at timestamptz DEFAULT now(), created_by text
);
-- Test-only hold point. The second connection probes whether a sale_items
-- UPDATE is blocked while the finalizer is already inside its refund INSERT.
CREATE FUNCTION public.phase646_test_pause_refund() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.sale_id=16 THEN
    PERFORM pg_advisory_lock(64616);
    PERFORM pg_sleep(4);
    PERFORM pg_advisory_unlock(64616);
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER phase646_test_pause_refund BEFORE INSERT ON public.refunds
  FOR EACH ROW EXECUTE FUNCTION public.phase646_test_pause_refund();
ALTER TABLE public.refunds ENABLE ROW LEVEL SECURITY;
CREATE POLICY refunds_sales ON public.refunds FOR ALL TO authenticated USING(true) WITH CHECK(true);
CREATE TABLE public.warehouse_stock (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES public.products(id),
  warehouse_id integer NOT NULL REFERENCES public.warehouses(id),
  stock integer NOT NULL DEFAULT 0 CHECK(stock>=0), min_stock integer DEFAULT 0,
  UNIQUE(product_id,warehouse_id)
);
CREATE FUNCTION public.sync_product_stock() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  UPDATE public.products SET stock=(SELECT coalesce(sum(stock),0) FROM public.warehouse_stock WHERE product_id=NEW.product_id)
  WHERE id=NEW.product_id;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_sync_product_stock AFTER INSERT OR UPDATE ON public.warehouse_stock
  FOR EACH ROW EXECUTE FUNCTION public.sync_product_stock();
CREATE TABLE public.stock_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint REFERENCES public.products(id), type text, qty integer,
  note text, created_by uuid, created_at timestamptz DEFAULT now()
);
CREATE TABLE public.loyalty_points (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint REFERENCES public.customers(id), points integer,
  type text, ref_type text, ref_id bigint, note text, created_at timestamptz DEFAULT now()
);
CREATE UNIQUE INDEX uq_loyalty_sale_reverse ON public.loyalty_points(ref_id) WHERE ref_type='sale_reverse';
CREATE TABLE public.chart_of_accounts (code text PRIMARY KEY, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE public.account_mapping (
  mapping_key text PRIMARY KEY, debit_account_code text REFERENCES public.chart_of_accounts(code),
  credit_account_code text REFERENCES public.chart_of_accounts(code), is_active boolean NOT NULL
);
CREATE TABLE public.journal_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_no text UNIQUE, doc_type text, doc_date date, description text,
  status text, total_debit numeric(14,2), total_credit numeric(14,2),
  source_table text, source_id bigint, created_by uuid, approved_by uuid,
  approved_at timestamptz,
  CHECK(total_debit=total_credit)
);
CREATE UNIQUE INDEX idx_je_source_unique ON public.journal_entries(source_table,source_id)
  WHERE source_table IS NOT NULL AND source_id IS NOT NULL;
CREATE FUNCTION public.check_period_not_locked() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RETURN NEW; END $$;
CREATE TRIGGER trg_check_period_locked BEFORE INSERT OR UPDATE OR DELETE ON public.journal_entries
  FOR EACH ROW EXECUTE FUNCTION public.check_period_not_locked();
CREATE TABLE public.journal_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id bigint NOT NULL REFERENCES public.journal_entries(id) ON DELETE CASCADE,
  line_no integer, account_code text REFERENCES public.chart_of_accounts(code),
  debit numeric(14,2) DEFAULT 0, credit numeric(14,2) DEFAULT 0, description text,
  CHECK(debit>=0 AND credit>=0)
);
CREATE FUNCTION public.enforce_je_lines_balance() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_id bigint;
BEGIN
  v_id := coalesce(NEW.entry_id,OLD.entry_id);
  IF EXISTS (SELECT 1 FROM public.journal_entries e WHERE e.id=v_id AND
    (e.total_debit IS DISTINCT FROM (SELECT coalesce(sum(debit),0) FROM public.journal_lines WHERE entry_id=v_id)
     OR e.total_credit IS DISTINCT FROM (SELECT coalesce(sum(credit),0) FROM public.journal_lines WHERE entry_id=v_id))) THEN
    RAISE EXCEPTION 'unbalanced journal lines';
  END IF;
  RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER trg_je_lines_balance AFTER INSERT OR UPDATE OR DELETE ON public.journal_lines
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.enforce_je_lines_balance();
CREATE TABLE public.customer_credit_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES public.customers(id), source_type text,
  source_id bigint, source_key text, amount numeric(14,2), note text,
  created_at timestamptz DEFAULT now(), created_by uuid
);
CREATE UNIQUE INDEX uq_ccl_source ON public.customer_credit_ledger(source_type,source_id) WHERE source_id IS NOT NULL;
CREATE UNIQUE INDEX uq_ccl_source_key ON public.customer_credit_ledger(source_type,source_key) WHERE source_key IS NOT NULL;
ALTER TABLE public.customer_credit_ledger ENABLE ROW LEVEL SECURITY;
CREATE POLICY ccl_staff_rw ON public.customer_credit_ledger FOR ALL TO authenticated USING(true) WITH CHECK(true);
CREATE POLICY ccl_deny_customer ON public.customer_credit_ledger AS RESTRICTIVE FOR ALL TO authenticated
  USING (NOT coalesce(public.is_customer_role(),false)) WITH CHECK (NOT coalesce(public.is_customer_role(),false));
GRANT USAGE ON SCHEMA public, auth TO authenticated,anon,service_role;
GRANT SELECT ON public.profiles TO authenticated;
-- Fixture-only visibility for behavioral assertions; the candidate migration
-- does not grant these permissions in production.
GRANT SELECT ON public.products,public.warehouse_stock,public.stock_movements,
  public.journal_entries,public.journal_lines,public.loyalty_points TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.customer_credit_ledger,public.refunds TO authenticated,service_role;
GRANT EXECUTE ON FUNCTION auth.uid(),public.is_admin(),public.is_customer_role() TO authenticated;

INSERT INTO public.profiles VALUES
  ('00000000-0000-0000-0000-000000000001','admin'),
  ('00000000-0000-0000-0000-000000000002','sales'),
  ('00000000-0000-0000-0000-000000000003','customer'),
  ('00000000-0000-0000-0000-000000000004','sales');
INSERT INTO public.customers VALUES (101,'ลูกค้าทดสอบ'),(102,'ลูกค้าคืนบางรายการ');
INSERT INTO public.products(id,stock) VALUES (44,3),(45,2);
INSERT INTO public.warehouses VALUES (2);
INSERT INTO public.warehouse_stock(product_id,warehouse_id,stock) VALUES (44,2,3),(45,2,2);
INSERT INTO public.sales(id,order_no,customer_id,customer_name,total_amount,subtotal,discount_amount,paid_amount,change_amount,credit_used_amount,vat_amount,vat_rate,is_credit)
 VALUES (9,'BSK-9',101,'ลูกค้าทดสอบ',90,100,10,90,0,0,0,0,false),
        (10,'BSK-10',102,'ลูกค้าคืนบางรายการ',150,150,0,150,0,0,0,0,false),
        (11,'BSK-11',101,'ลูกค้า VAT เก่า',107,100,0,107,0,0,7,7,false),
        (12,'BSK-12',102,'ลูกค้า JV fail',50,50,0,50,0,0,0,0,false),
        (13,'BSK-13',102,'ลูกค้ายอดไม่ตรง',99,100,0,99,0,0,0,0,false),
        (15,'BSK-15',102,'ลูกค้าใช้แต้มแล้ว',40,40,0,40,0,0,0,0,false),
        (16,'BSK-16',102,'ทดสอบแก้รายการพร้อมกัน',20,20,0,20,0,0,0,0,false),
        (17,'BSK-17',101,'บิลเงินสดจำลอง',30,30,0,30,0,0,0,0,false);
INSERT INTO public.sale_items VALUES
  (81,9,44,'สินค้า A',1,100,100,2),
  (82,10,44,'สินค้า A',1,100,100,2),
  (83,10,45,'สินค้า B',1,50,50,2),
  (84,11,44,'สินค้า A',1,100,100,2),
  (85,12,45,'สินค้า B',1,50,50,2),
  (86,13,44,'สินค้า A',1,100,100,2),
  (87,15,45,'สินค้า B',1,40,40,2),
  (88,16,45,'สินค้า B',1,20,20,2);
-- A real full-sale candidate needs both the original stock deduction trail
-- and its approved sale journal; otherwise the database must park it for review.
INSERT INTO public.stock_movements(product_id,type,qty,note)
  VALUES (44,'sale',1,'ขายบิล BSK-9 — คลัง: 2');
INSERT INTO public.journal_entries
  (doc_no,doc_type,doc_date,description,status,total_debit,total_credit,source_table,source_id)
  VALUES ('SALE-9','sale',CURRENT_DATE,'original sale 9','approved',90,90,'sales',9),
         ('SALE-12','sale',CURRENT_DATE,'original sale 12','approved',50,50,'sales',12),
         ('SALE-15','sale',CURRENT_DATE,'original sale 15','approved',40,40,'sales',15),
         ('SALE-16','sale',CURRENT_DATE,'original sale 16','approved',20,20,'sales',16);
INSERT INTO public.loyalty_points(customer_id,points,type,ref_type,ref_id,note)
  VALUES (101,5,'earn','sale',9,'earn sale 9'),
         (102,5,'earn','sale',15,'earn sale 15'),
         (102,3,'redeem','sale',12,'spent points after sale 15');
INSERT INTO public.chart_of_accounts(code) VALUES ('4110'),('2180');
INSERT INTO public.account_mapping VALUES
  ('refund_credit','4110','2180',true),('refund_exchange','4110','2180',true);
